name = "clear-chain-api"
compatibility_date = "2023-12-01"
main = "src/index.ts"
minify = true

[dev]
port = 3000

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
SUPABASE_URL = "https://cgnmqnohbudnwolkvsae.supabase.co"
vars = { ENVIRONMENT = "development" }

[observability.logs]
enabled = true
